-- AlterTable
ALTER TABLE `FoodDictionary` MODIFY `type` ENUM('FIBER', 'PROTEIN', 'COMPLEX_CARB', 'SIMPLE_CARB', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `FoodItem` MODIFY `type` ENUM('FIBER', 'PROTEIN', 'COMPLEX_CARB', 'SIMPLE_CARB', 'OTHER') NOT NULL;
